---
version: '2.6'

services:
  sgp-api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - "SERVER_PORT=4000" # port to listen on
      - "NODE_ENV=production" 
      - "SERVER_HOST=0.0.0.0" # listen on all interfaces
      - "SERVER_TIMEOUT=10000" #timeout in ms
      - "TOKEN=" #Set your bearer token here
    command: npm start
